language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install: "git clone https://github.com/eugene-eeo/tinydb && cd tinydb && git checkout 2.0 && cd -"
script: py.test tests.py
